### PR TITLE
Fail gracefully and log missing config keys at startup in dev mode

### LINKED ISSUE #361: fail more gracefully and informative in quarkus:dev
instead of hard failing when the extension runs and you don't have the 4 properties set we recommend that
in devmode that you log a warn/error that configuration is missing and actually in the error message have the missing properties.

That makes it so you as the user does not need to go search the documentation for the keys.

### PR DESCRIPTION
**Pull request by gwenneg**
Fixes #361.

### CODE REVIEW

File: runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchHandlerValueFactory.java [hunk 1]
```diff
@@ -42,9 +45,20 @@ public RuntimeValue<Optional<Handler>> create(final LoggingCloudWatchConfig conf
...
+        if (!errors.isEmpty()) {
+            String errorMsg = "The Quarkus Logging Cloudwatch extension is unable to start because of missing configuration values: "
+                    + String.join(", ", errors);
+            if (ProfileManager.getLaunchMode() == DEVELOPMENT) {
+                LOGGER.error(errorMsg);
+                return new RuntimeValue<>(Optional.empty());
+            } else {
+                throw new IllegalStateException(errorMsg);
+            }
+        }
```
Comment (gwenneg) [inline runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchHandlerValueFactory.java:60]: @maxandersen Is this what you meant in #361?

Comment (gwenneg) [reply runtime/src/main/java/io/quarkiverse/logging/cloudwatch/LoggingCloudWatchHandlerValueFactory.java:60]: I'm not sure the hard fail is okay in prod mode but you only mentioned changing the behavior is dev mode IIUC.
